### ISSUE TITLE
Composition API not instantiated fast enough to be used outside of components

### ISSUE THREAD

**Issue by DarkLite1** [quasarframework/quasar-starter-kit#110] opened 2020-05-20 08:16 UTC
**Describe the bug**

On request of @IlCallo we create this issue:

We created a composition function that contains logic to verify if a user is logged on or not. This function would also be called in the file `/router/index.ts` to safe guard routes.

At the moment the composition API is loaded from within in a Quasar boot file. This works fine when using composition functions in Vue components but not when you want to access them elsewhere. 

**To Reproduce**

1. Create a boot file that loads the composition API (I believe the starter kit does this)
```js
// boot/CompositionAPI
import VueCompositionApi from '@vue/composition-api';
import { boot } from 'quasar/wrappers';

export default boot(({ Vue }) => {
  Vue.use(VueCompositionApi);
});
```
2. Create a composition function
```js
// useAccount.ts
import { computed, ref } from '@vue/composition-api'
import { isInternetExplorer } from 'src/services/utils/utilsService'
import { Screen } from 'quasar'
import { auth, getAllScopes } from 'src/services/auth/authService'

const isLoginPopup = Screen.lt.sm || isInternetExplorer ? false : true
const accountID = ref('')

export const setAccountID = () => {
  const account = auth.getAccount()

  if (account) {
    accountID.value = account.idTokenClaims.oid
  } else {
    accountID.value = ''
  }
}

export const useAccount = () => {
  const loading = ref(false)
  const disabled = ref(false)

  const login = async () => {
    loading.value = true
    disabled.value = true

    const allScopes = getAllScopes()

    if (isLoginPopup) {
      try {
        await auth.loginPopup(allScopes)
      } finally {
        setAccountID()
        disabled.value = false
        loading.value = false
      }
    } else {
      auth.loginRedirect(allScopes) // page reload
    }
  }
  const logout = () => {
    auth.logout()
  }
  return {
    accountID: computed(() => accountID.value),
    isAuthenticated: computed(() => Boolean(accountID.value)),
    loading: computed(() => loading.value),
    disabled: computed(() => disabled.value),
    login, logout,
  }
}
```
3. Try to use the computed property `isAuthenticated` outside a component:
```js
// /router/index.ts
import { route } from 'quasar/wrappers'
import VueRouter from 'vue-router'
import routes from './routes'
import { useAccount } from 'src/comp-functions/useAccount'

const { isAuthenticated } = useAccount()

export default route(function ({ Vue }) {
Vue.use(VueRouter)

  const Router = new VueRouter({
    scrollBehavior: () => ({ x: 0, y: 0 }),
    routes,
    mode: process.env.VUE_ROUTER_MODE,
    base: process.env.VUE_ROUTER_BASE,
  })

  Router.beforeEach((to, from, next) => {
    if (isAuthenticated.value || to.path === '/' || to.path === '/login') {
      next()
    } else {
      next('/login')
    }
  })

  return Router
})

```
4. See error:

> Uncaught Error: [vue-composition-api] must call Vue.use(plugin) before using any function

**Expected behavior**
Simply being able to use the computed property from the composition function.

**Additional context**
See also [StackOverflow](https://stackoverflow.com/questions/61885716/uncaught-error-vue-composition-api-must-call-vue-useplugin-before-using-any)..

**Workaround**
1. Create a file to load the plugin:
```js
// services/vue/CompositionApi.ts
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
```
2. Load the composition API as soon as possible:
```js
// /router/index.ts
import 'src/services/vue/CompositionApi'

import { route } from 'quasar/wrappers'
import VueRouter from 'vue-router'
import routes from './routes'
```

**Comment by IlCallo** [comment] 2020-05-20 09:04
I actually meant "on the main repo", but it's ok.
I want to explore if there is a better (and Quasar-stylish) way to solve this problem, and eventually update the starter kit to support this scenario (I saw it can be pretty common).

The problem arise only with compatibility composition API package because it's a plugin.
Vue3 version is a standalone package and should not have this problem

**Comment by yusufkandemir** [comment] 2020-05-21 02:53
## The problem
There is a simple reason behind it. The [router is created](https://github.com/quasarframework/quasar/blob/e7aec371502850243227feb69c7e6b2a7eb41dc5/app/templates/entry/client-entry.js#L89)(also see [here](https://github.com/quasarframework/quasar/blob/e7aec371502850243227feb69c7e6b2a7eb41dc5/app/templates/entry/app.js#L45-L47)) before the [boot files are executed](https://github.com/quasarframework/quasar/blob/e7aec371502850243227feb69c7e6b2a7eb41dc5/app/templates/entry/client-entry.js#L109-L134) so that the router can be accessed from boot files.

## The way to the solution
The solution would be simply moving the router checking logic to a boot file(its boot order must be after `composition-api`). But there is one extra thing to keep in mind. Since importing `src/comp-functions/useAccount` produces a side effect(`const accountID = ref('')`) and boot functions are executed way after they are imported, the error would still exist(See where the error would occur in the code below). You need to check [entry/client-entry.js](https://github.com/quasarframework/quasar/blob/dev/app/templates/entry/client-entry.js) and [entry/app.js](https://github.com/quasarframework/quasar/blob/dev/app/templates/entry/app.js) files to get a better understanding.

```js
// boot/auth.js or whatever
import { boot } from 'quasar/wrappers'

// This will still cause issues, see explanation below for solution
import { useAccount } from 'src/comp-functions/useAccount'

export default boot(({ router }) => {
  const { isAuthenticated } = useAccount()

  router.beforeEach((to, from, next) => {
    if (isAuthenticated.value || to.path === '/' || to.path === '/login') {
      next()
    } else {
      next('/login')
    }
  })
})
```

To overcome this problem that is caused by a side effect, we ironically need to make `boot/composition-api.js` produce a side effect. It should be modified as the following:

```js
// boot/composition-api.js
import VueCompositionApi from '@vue/composition-api'

// Side effect
Vue.use(VueCompositionApi)
```

## An alternative solution

An alternative solution would be to eliminate the side effect in `src/comp-functions/useAccount`, by doing something like:

```js
// src/comp-functions/useAccount
// ...
let accountID

// Other functions shouldn't be called before calling this
export const setup = () => {
  accountID = ref('')
}

// ...
```

```js
// boot/auth.js
import { boot } from 'quasar/wrappers'

import { setup, useAccount } from 'src/comp-functions/useAccount'

export default boot(({ router }) => {
  // Initialize the account state first
  setup()

  // Then use it afterwards
  const { isAuthenticated } = useAccount()

  router.beforeEach((to, from, next) => {
    if (isAuthenticated.value || to.path === '/' || to.path === '/login') {
      next()
    } else {
      next('/login')
    }
  })
})
```

I guess you would need a function like this for initializing states when doing SSR anyways(I am not 100% sure about this), so using the latter approach should be more future-proof with the cost of requiring more responsibility.

_Note: I am just writing these things out of mind, somethings may not be correct. So, be extra sure to test different approaches, and correct me if anything is wrong._

**Comment by DarkLite1** [comment] 2020-05-21 08:04
Thank you for looking into this but loading the composition API from a boot file simply didn't work. 

There are some things I always try to do, Keep logic together, i.e. router logic in the router file. Keep things consistent, why call a `setup()` method when the global state is defined in a `ref` within the file `useAccount.ts`?

Anyway, I sound a bit ungrateful but I'm not, I really appreciate your input. I've just spent too much time on this and now I use the KISS solution, just load the plugin first from the router file. This way I can use composition functions everywhere I want, without thinking when boot files will be executed in the apps life-cycle.  On a side note, this problem will disappear when Vue 3 will be released.

**Comment by yusufkandemir** [comment] 2020-05-21 12:13
> Thank you for looking into this but loading the composition API from a boot file simply didn't work.

@DarkLite1 you are welcome. Don't get me wrong but are you sure you didn't quickly skip over the text?
This:
> To overcome this problem that is caused by a side effect, we ironically need to make boot/composition-api.js produce a side effect. It should be modified as the following:
> ```js
> // boot/composition-api.js
> import Vue from 'vue'
> import VueCompositionApi from '@vue/composition-api'
> 
> // Side effect
> Vue.use(VueCompositionApi)
> ```
is not same as this:
```js
// boot/CompositionAPI
import VueCompositionApi from '@vue/composition-api'
import { boot } from 'quasar/wrappers'

export default boot(({ Vue }) => {
  Vue.use(VueCompositionApi)
})
```
So, combined with moving router logic into a boot file, it will work.

### About keeping the logic together

> There are some things I always try to do, Keep logic together, i.e. router logic in the router file.
> ... now I use the KISS solution, just load the plugin first from the router file.

It's good to keep logic together, but you can keep the router middleware logic in a boot file too. The only difference is you move it to another file, logic stays the same. One would defend a big `main.js` file instead of boot files to keep setup logic together in this manner, you know what I mean? One day you would need another plugin or library that requires a setup step, you would also need to call it from your router file, it would eventually grow into a mess. I am just trying to tell you about the best practices.

### About `setup()`
> Keep things consistent, why call a setup() method when the global state is defined in a ref within the file useAccount.ts?

I think my answer is clear on this. I just need somebody to prove my point, because I don't know much about SSR and I don't want to spread wrong information like it's the truth. Also, I offered this as an alternative solution, with its pros and cons. Looking at this from a different point, one would keep all global state side effects in setup functions and call it "the consistent way".

> I guess you would need a function like this for initializing states when doing SSR anyways(I am not 100% sure about this), so using the latter approach should be more future-proof with the cost of requiring more responsibility.

**Comment by DarkLite1** [comment] 2020-05-22 12:35
Oops! Indeed, I read that wrong. Your approach on the boot file is a different one than the one I tried. So yes, this might work. In any case, for me this is a temporary solution until Vue 3 is supported by Quasar Framework. When it is, I simply need to remove the import file and I'm done. 

Thanks again for giving this detailed input. Leaving this open for @IlCallo to see what he can take away from this.

**Comment by DarkLite1** [comment] 2020-05-24 10:37
Just for clarity's sake I tried your first suggestion in "The way to the solution":

```js
// /boot/VueCompositionApi.js
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
```

```js
// /boot/auth.js
import { boot } from 'quasar/wrappers'
import { useAccount } from 'src/comp-functions/useAuth'

export default boot(({ router }) => {
  const { setAccountID, isAuthenticated } = useAccount()
  setAccountID()

  router.beforeEach((to, from, next) => {
    if (isAuthenticated.value || to.path === '/' || to.path === '/login') {
      next()
    } else {
      next('/login')
    }
  })
})
```

No luck I'm afraid  this still yields the same error that Vue can't use a composition function before the CompositionAPI is instantiated:

![image](https://user-images.githubusercontent.com/10828570/82751871-84759e00-9dba-11ea-8b59-3715816b81ef.png)

@yusufkandemir regarding best practices I agree with you. Separate files in the boot folder might be a good idea to keep an overview. Thanks again for helping out.

**Comment by yusufkandemir** [comment] 2020-05-24 11:48
> This seems logical as the boot file order is not guaranteed
@DarkLite1 it is guaranteed, even the async boot files are awaited before executing the next one. So, this shouldn't be a problem. Can you share your final `src/comp-functions/useAuth` file and the `boot` section in `quasar.conf.js` please? I would like to guess what's going on.

Also, it would be extra nice if you also try the `alternative solution` if you have some time. But use the old version of `/services/vue/CompostionApi.ts`, two solutions are different from each other.

**Comment by DarkLite1** [comment] 2020-05-24 13:00
How is the order of the boot files defined? Because if one is sure to be called after the other, there should be some logic to decide which boot file to call first. As I said before, loading the plugin from within a boot file, exactly as I copied it above (without `boot`), doesn't work.

You can find all my current code [in my repo](https://github.com/DarkLite1/hip) and this is the [useAuth.ts file](https://github.com/DarkLite1/hip/blob/master/src/services/auth/authService.ts).

**Comment by yusufkandemir** [comment] 2020-05-24 14:00
@DarkLite1 boot files are executed in the order they are in `quasar.conf.js > boot`. For example,

https://github.com/DarkLite1/hip/blob/6ca86869d9469e1561d94f34f9da603c500561e9/quasar.conf.js#L18
```js
boot: ['i18n', 'auth'],
```

`i18n` is executed first, then the `auth` one. If a promise is returned from a boot file, the next one will be executed after the promise is resolved, there aren't any in this case.

> exactly as I copied it above (as you showed without the boot import)

Boot files must be referenced from `boot` key in `quasar.conf.js`, otherwise they won't be imported and executed(This gives flexibility to conditionally run boot files). If you don't default export a function from the boot file and reference it in the `boot` section, it will be imported (any linear code will be executed (e.g. variable definitions, function calls, exports, etc.)) but since there isn't any default function to execute, the non-existent boot function will not be executed (We take advantage of this in **The way to the solution**).
So, I didn't feel the need to express the need of importing it. So, it would probably work if you added it to the `boot` key(it must be before `auth` to keep the boot order `boot: ['i18n', 'composition-api', 'auth']`).

**Comment by DarkLite1** [comment] 2020-05-24 14:11
I did add it to the `boot` array but, as it usually goes, in the wrong order. You are correct, another way to get this to work is correcting the order that the `boot` files get loaded:

```js
// order is important!
boot: ['VueCompositionApi', 'auth', 'i18n'],
```

This fixed it for me too. Maybe there should be a small comment saying that the order is important of the `boot` array within `quasar.conf.js`. It would've saved me a lot of trouble lol.

@yusufkandemir thank you for giving this valuable feedback. Much appreciated :)

**Comment by IlCallo** [comment] 2021-05-16 13:18
Vue Composition API will be merged back into Vue 2.x core, closing as this won't be a problem in the near future

**Closed by IlCallo** 2021-05-16 13:18 UTC
Labels: bug
